### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by juharris** [2CATteam/AmbigramGenerator#1]
This is really great, thanks for building this and making it so easy to use. I do have a question about minimizing the numbers of objects so that I can lay them out in a line.
If I do CH+CL, then there's 2 objects, that's great.
Then R+A, there's just 1 object, great.
Now if I do CHR+CLA, then there's 4 objects. Why not 2 + 1 = 3 objects?

So it seems like if I want 2 strings that are the same length and I want to minimize the number of objects, so that I can put the objects in a line, then I can do it manually one letter at a time. What do you think about adding this as an option or tweaking the generation algorithm?

**Comment by 2CATteam** [comment]
Hey there! Sorry it's taken a bit of time to get back to you.

Honestly, I'm not particularly interested in adding that option at the moment, just because generators which DO work like that already exist:

https://www.thingiverse.com/thing:3516901

https://www.thingiverse.com/thing:2936919

When I made this, I wasn't terrible interested in minimizing the number of objects; rather, I was trying to achieve an effect where it wasn't clear that the model was even SUPPOSED to make a word, until you saw it from the right perspective. That's not to say minimizing the number of objects isn't a good idea - it's WAY easier to put together, and typically FAR more stable. However, considering that these other generators already accomplish that, I'm not sure what benefit adding the feature to mine would have.

I'm open to being convinced that it'd be worth it, but as-is, I'm not, due to the others already doing that.

**Comment by juharris** [comment]
No worries, I've been busy too, thanks for getting back to me.

Thanks for sharing those. I saw one or one like them before but the customizer in thingiverse isn't working anymore, I saw a bunch of posts online about how it doesn't work for anyone. Anyway, your site is much easier and fast.
That makes sense that it's not in your design to minimize the number of objects. I agree that the effect does look neat.

**Comment by 2CATteam** [comment]
Really? That's weird. Looking at it myself, it seems like it takes a LONG time to load, but it eventually does show up. At least, most of the time.

Knowing that it has some loading issues, though, is enough for me to take the time to add this feature. Let's see how long it takes!

**Comment by juharris** [comment]
Yeah the customizer opens, you can tweak some settings, but it won't generate a build for you after you submit the design.

Thanks so much!

**Comment by 2CATteam** [comment]
Should be live now! The base is still just rectangular, but I'm not too concerned about that as of right now.

Thanks for the suggestion! It was a fun little challenge to implement this feature.

**Comment by juharris** [comment]
Wow that was fast! Thanks so much!
A friend did the single letters manually 2 weeks ago for a puzzle to make for a friend. We gave him the letters over a few days while he tried to figure out what it could spell. It was much more simple to solve as a puzzle this way than it would be will all those pieces. It was also easier for people passing by it quickly to realize that it says something.

I just tried it out and the new option seems to work well. It even works well with words that have different lengths.

**Comment by 2CATteam** [comment]
Glad it helps! And glad you found a workaround, even if it's a little clunky!

And yeah, the main struggle was getting it to work for different length words. I could have just restricted it to only same-length strings, but I didn't really want to. It has some weird problems with cases where one word is 2+ times the length of the other, but it's still functional, it's just weird, so I'm not worried.

**Comment by 2CATteam** [comment]
Scratch that, I found the issue there and fixed it
